<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                                    => __DIR__ . '/Module.php',
    'Application\Controller\CronController'                 => __DIR__ . '/src/Application/Controller/CronController.php',
    'Application\Controller\EditController'                 => __DIR__ . '/src/Application/Controller/EditController.php',
    'Application\Controller\IndexController'                => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Controller\UploadController'               => __DIR__ . '/src/Application/Controller/UploadController.php',
    'Application\Entity\LinkToOrder'                        => __DIR__ . '/src/Application/Entity/LinkToOrder.php',
    'Application\Entity\MainContent'                        => __DIR__ . '/src/Application/Entity/MainContent.php',
    'Application\Entity\YoutubeVideo'                       => __DIR__ . '/src/Application/Entity/YoutubeVideo.php',
    'Application\Factory\Controller\CronControllerFactory'  => __DIR__ . '/src/Application/Factory/Controller/CronControllerFactory.php',
    'Application\Factory\Controller\IndexControllerFactory' => __DIR__ . '/src/Application/Factory/Controller/IndexControllerFactory.php',
    'Application\Form\ImgUploadForm'                        => __DIR__ . '/src/Application/Form/ImgUploadForm.php',
    'Application\Model\Check'                               => __DIR__ . '/src/Application/Model/Check.php',
    'Application\Model\Email'                               => __DIR__ . '/src/Application/Model/Email.php',
);
