<style>
    a {
        display: inline-block;
        border: 1px solid #000000;
        padding: 5px;
        margin: 5px;
    }

    img {
        width: 150px;
    }
</style>
<div class="content row">
    <div class="col col-lg-12">
        <?php
        foreach ($this->result as $img) {
            $explode = explode('/', $img);
            $name    = $explode[count($explode) - 1];

            echo '<a onclick="selectFile(this)" href="' . $img .'"><img class="img-responsive" src="' . $img . '" alt="">' . $name . '</a>';
        }
        ?>
    </div>
</div>
<script>
    function selectFile(a) {
        window.opener.CKEDITOR.tools.callFunction(<?php echo $_GET['CKEditorFuncNum']?>, a.href, '');
        self.close();
    }
</script>