<?php echo $this->doctype(); ?>

<html lang="ru">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('LegalServiceRomania - Admin')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/admin/admin.min.css')
        ->prependStylesheet($this->basePath() . '/css/style.min.css')
        ->prependStylesheet($this->basePath() . 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/script.min.js')
        ->prependFile($this->basePath() . '/ckeditor/ckeditor.js')
        ->prependFile($this->basePath() . '/js/jquery.pin.min.js')
        ->prependFile($this->basePath() . 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js')
        ->prependFile($this->basePath() . 'http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>
<?php if ($this->userRole === 'admin') : ?>
    <div class="control" style="width: 50px; font-size: 28px; background: #FFD600; position: fixed; top: 0; left: 0; z-index: 99999">
        <a style="display: block; padding-left: 10px; border-bottom: 1px solid #000000" href="/edit" data-toggle="tooltip" data-placement="right" title="Управление"><i class="glyphicon glyphicon-wrench"></i></a>
        <a style="display: block; padding-left: 10px;" href="/user/logout" data-toggle="tooltip" data-placement="right" title="Выйти"><i class="glyphicon glyphicon-arrow-left"></i></a>
    </div>
<?php endif; ?>
<div class="container">
    <div class="content row header">
        <div class="col col-sm-5">
            <section id="branding">
                <a href="/" class="brand">
                    <div class="bottom-logo">
                        <div class="top-logo"></div>
                    </div>
                </a>
            </section>
        </div>
        <div class="col col-sm-3 col-sm-offset-4 contacts">
            <p class="phone"><span class="glyphicon glyphicon-earphone"></span> +38(096)220-23-93</p>
            <p class="phone"><span class="glyphicon glyphicon-earphone"></span> +38(096)220-23-93</p>
        </div>
    </div>
    <div class="content row">
        <div class="col col-lg-12">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navigation">
                    <span class="sr-only">Главная навигация</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="main-navigation" class="collapse navbar-collapse pinned">
                <?php echo $this->navigation('navigation')->menu()->setULClass('nav nav-justified main-nav'); ?>
            </div>
            <div class="menu-gradient"></div>
        </div>
    </div>
    <?php echo $this->content; ?>
    <div class="content row">
        <footer id="footer" class="col col-lg-12 text-center">
            <p>&copy; <?php echo date('Y') ?> by LegalServiceRomania. All rights reserved.</p>
        </footer>
    </div>
</div> <!-- /container -->
</body>
</html>
