<?php
$title = 'Главная';
$this->headTitle($title);
?>
<div class="content row main home-page">
    <section class="col col-md-9 col-md-push-3">
        <div class="flash-messager">
            <?php if (count($this->flashMessages)) : ?>
                <ul class="list-unstyled">
                    <?php foreach ($this->flashMessages as $msg) : ?>
                        <li><?php echo $msg; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
        <div class="check-form holder">
            <h3 class="text-center">Проверьте свое досье</h3>
            <div class="form center-block">
                <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('home'));
                $form->prepare();

                echo $this->form()->openTag($form);
                echo $this->formRow($form->get('name')),
                     $this->formRow($form->get('number')),
                     $this->formSubmit($form->get('submit'));
                echo $this->form()->closeTag();
                ?>
            </div>
            <!-- Check order form -->
            <div class="checked-data hide">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Фамилия Имя</th>
                            <th>№ досье/год</th>
                            <th>Приказ/Дата</th>
                            <th>№ в приказе</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div><!-- /Check order form -->
        </div>
        <div id="slide-carousel" class="holder carousel slide hidden-sm hidden-xs" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#slide-carousel" data-slide-to="0" class="active"></li>
                <li data-target="#slide-carousel" data-slide-to="1"></li>
                <li data-target="#slide-carousel" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <img src="/img/carousel/pict1.png" alt="">
                </div>
                <div class="item">
                    <img src="/img/carousel/pict2.png" alt="">
                </div>
                <div class="item">
                    <img src="/img/carousel/pict3.png" alt="">
                </div>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#slide-carousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#slide-carousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
        <div class="main-content holder">
            <?php echo $this->content ?>
        </div>
    </section>
    <?php echo $this->aside; ?>
</div>